version: 2
jobs:
  build-image:
    docker:
      # specify the version you desire here
      - image: google/cloud-sdk:latest

    working_directory: ~/repo

    steps:
      - run:
          name: Authenticate with gcloud
          command: |
            echo $GCLOUD_DOCKER_PRIVATE_CREDENTIALS > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json

      # if authentication succeeded - checkout code
      - checkout

      # starts a remote docker environment to run docker commands
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build docker image and push image to GCR
          command: |
            gcloud auth configure-docker --quiet
            TAG="11.10.0"
            docker build -t docker-image-node-gcloud .
            docker tag docker-image-node-gcloud eu.gcr.io/dnt-docker-registry-public/docker-image-node-gcloud:latest
            docker tag docker-image-node-gcloud eu.gcr.io/dnt-docker-registry-public/docker-image-node-gcloud:$TAG
            docker push eu.gcr.io/dnt-docker-registry-public/docker-image-node-gcloud:latest
            docker push eu.gcr.io/dnt-docker-registry-public/docker-image-node-gcloud:$TAG

      - run:
          name: Notify Slack on failure
          when: on_fail
          command: |
            chmod +x .circleci/notify-slack.sh
            ./.circleci/notify-slack.sh false Build image failed
      - run:
          name: Notify Slack on sucess
          when: on_success
          command: |
            chmod +x .circleci/notify-slack.sh
            ./.circleci/notify-slack.sh true Build image succeeded

workflows:
  version: 2
  build-image:
    jobs:
      - build-image:
          context: dnt-k8s-prod
          filters:
            branches:
              only: /^master$/
